apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alerter.fullname" . }}-config
  labels:
    {{- include "alerter.labels" . | nindent 4 }}
data:
  config.yaml: |
    listen:
      host: "0.0.0.0"
      port: 8080

    dingtalk:
      enabled: {{ .Values.alerter.dingtalk.enabled }}

    feishu:
      enabled: {{ .Values.alerter.feishu.enabled }}
      secret: {{ .Values.alerter.feishu.secret | quote }}

